### ISSUE TITLE
can't deserialize multisigned transaction

### ISSUE THREAD

**Issue by xiewenlong1202** [ontio/ontology-python-sdk#129]
I use the multisig of the sdk package, in the following step
1. in machine A, generate a raw transaction and sign with the payer
2.use the serialize function of the Transaction object to get the hex representation of the tx
3.use 2 of 3 multisign account to sign the tx and after that deserilize the transaction
4.after decode the transaction, information has been lost

**Comment by NashMiao** [comment]
Hi, transaction deserialize bug has fixed, you can try ontology-python-sdk v0.1.19.
