### ISSUE TITLE
cant't get_gcm_decoded_private_key  

### ISSUE THREAD

**Issue by ticotic** [ontio/ontology-python-sdk#156]
Raise Exception when i call get_gcm_decoded_private_key :

`Traceback (most recent call last):
  File "D:/Projects/ontology-python-sdk/test/test_tt.py", line 12, in <module>
    SignatureScheme.SHA256withECDSA)
  File "D:\Projects\ontology-python-sdk\ontology\account\account.py", line 156, in get_gcm_decoded_private_key
    raise SDKException(ErrorCode.decrypt_encrypted_private_key_error)
ontology.exception.exception.SDKException: (51017, 'Account Error, decrypt encrypted private key error.')`

1.Create account by Ontology  (Not SDK)
2.Use this account information  (  address, salt, key, password  ) call   ontologt-python-sdk/account/account.py   Class Account  def get_gcm_decoded_private_key
3.SDK raise Exception

My account works well on ontology.Could you please help me check this Exception ?

**Comment by ticotic** [comment]
> Traceback (most recent call last):
  File "D:/Projects/ontology-python-sdk/test/test_tt.py", line 12, in <module>
    SignatureScheme.SHA256withECDSA)

  >File "D:\Projects\ontology-python-sdk\ontology\account\account.py", line 156, in get_gcm_decoded_private_key
    
>raise SDKException(ErrorCode.decrypt_encrypted_private_key_error)
ontology.exception.exception.SDKException: (51017, 'Account Error, decrypt encrypted private key error.')

**Comment by ticotic** [comment]
![image](https://user-images.githubusercontent.com/45810218/50504599-a5dd3800-0aa9-11e9-819a-0cc2ccc2dd5c.png)

**Comment by ticotic** [comment]
![image](https://user-images.githubusercontent.com/45810218/50504620-c7d6ba80-0aa9-11e9-88d3-455c1a3e24e0.png)

**Comment by NashMiao** [comment]
Hi, This is an bug in current source code, but not exist in published pypi package. So, you can try again by using pypi package.
