### ISSUE TITLE
Asynchronous support

### ISSUE THREAD

**Issue by binaryflesh** [ontio/ontology-python-sdk#235]
The SDK does not support streaming functionality. To support streaming, non-blocking I/O must be in place

**Comment by NashMiao** [comment]
In fact, the websocket interface is implement based on asyncio.

In addition, If you need asynchronous RPC and Restful interface, you can implement this in high level.

I don't think provide asynchronous RPC and Restful interface in SDKs level is necessary.

Users have right to decide which way is they need by themselves.

**Comment by NashMiao** [comment]
Do you have any suggestions about how to provide two type of RPC & Restful interface in an Pythonic way?

**Comment by NashMiao** [comment]
@binaryflesh Thanks for your suggestion. Now, we decide to support asynchronous RPC and Restful interface. This will help `ontology-python-sdk` to provide unified network interface.
