### ISSUE TITLE
Remove shebangs and encoding strings

### ISSUE THREAD

**Issue by binaryflesh** [ontio/ontology-python-sdk#236]
Files that are not directly executed on the command line do not need a shebang, e.g. '#/usr/bin/env python3' and since [PEP 3120](https://www.python.org/dev/peps/pep-3120/) there is no reason to use '# coding: utf-8' at beginning of file.

**Comment by NashMiao** [comment]
In fact, some code may need to executed in the command line. [Here](https://dev-docs.ont.io/#/docs-cn/ontology-cli/21-show-tx) is an example form our document center.

```shell
$ python
>>> from ontology.utils.contract_data import ContractDataParser
>>> ContractDataParser.to_int('14')
20
>>> ContractDataParser.to_b58_address('46b1a18af6b7c9f8a4602f9f73eeb3030f0c29b7')
'ANDfjwrUroaVtvBguDtrWKRMyxFwvVwnZD'
>>> ContractDataParser.to_int('14')
20
>>> ContractDataParser.to_b58_address('feec06b79ed299ea06fcb94abac41aaf3ead7658')
'Af1n2cZHhMZumNqKgw9sfCNoTWu9de4NDn'
>>> ContractDataParser.to_int('08')
8
>>> ContractDataParser.to_utf8_str('7472616e73666572')
'transfer'
>>> ContractDataParser.op_code_to_int('51')
1
>>> ContractDataParser.to_int('16')
22
>>> ContractDataParser.to_utf8_str('4f6e746f6c6f67792e4e61746976652e496e766f6b65')
'Ontology.Native.Invoke'
>>> len('Ontology.Native.Invoke')
22
```

I add an example about how to deserialize `payload` in `Transaction` because many developer ask this question in WeChat group.

**Comment by binaryflesh** [comment]
by running from command line I meant ran as ```# ./setup.py``` where a shebang would be utilized.

**Comment by NashMiao** [comment]
OK, I know what you mean, I had approved these changes. Thanks for your contribution. something needs further confirmation in [that PR](https://github.com/ontio/ontology-python-sdk/pull/238), let's finish it.

**Comment by NashMiao** [comment]
I has finished this job, thanks for your contribution. https://github.com/ontio/ontology-python-sdk/pull/248
