### ISSUE TITLE
Move single file packages to root directory

### ISSUE THREAD

**Issue by binaryflesh** [ontio/ontology-python-sdk#239]
There are several packages in question that are not utilizing any [special properties of a package](https://www.python.org/dev/peps/pep-0382/). By moving these to the root directory there is one less directory and file present in the project making it easier to navigate

**Comment by NashMiao** [comment]
I agree what you said, but this is an incompatible update. Besides, we may need to maintain consistency with other SDKs in ontology. Anyway, I will consider your suggestion seriously. Can you provide me a list about these packages?

**Comment by binaryflesh** [comment]
closing, opening up another issue with more specific proposal

**Comment by NashMiao** [comment]
OK, thanks.
