### ISSUE TITLE
no attribute 'set_rpc' & 'NeoVm' object is not callable

### ISSUE THREAD

**Issue by kenneth** [ontio/ontology-python-sdk#240]
```
Traceback (most recent call last):
  File "get_name.py", line 5, in <module>
    sdk.set_rpc(remote_rpc_address)
AttributeError: 'OntologySdk' object has no attribute 'set_rpc'
```

**Comment by kenneth** [comment]
```
Traceback (most recent call last):
  File "oep4_balance.py", line 13, in <module>
    oep4 = sdk.neo_vm().oep4()
TypeError: 'NeoVm' object is not callable
```

**Comment by NashMiao** [comment]
> ```
> Traceback (most recent call last):
>   File "oep4_balance.py", line 13, in <module>
>     oep4 = sdk.neo_vm().oep4()
> TypeError: 'NeoVm' object is not callable
> ```

You should use  `sdk.neo_vm.oep4()`.

**Comment by NashMiao** [comment]
> ```
> Traceback (most recent call last):
>   File "get_name.py", line 5, in <module>
>     sdk.set_rpc(remote_rpc_address)
> AttributeError: 'OntologySdk' object has no attribute 'set_rpc'
> ```

You should use one of the following interface, or all of them if you needed:

```python
sdk.rpc.set_address()
sdk.restful.set_address()
sdk.websocket.set_address()
```

Besides, If you want to connect to polaris test net or main net, the following interface will be more beautiful:

```python
sdk.rpc.connect_to_test_net()
sdk.restful.connect_to_test_net()
sdk.websocket.connect_to_test_net()
sdk.rpc.connect_to_main_net()
sdk.restful.connect_to_main_net()
sdk.websocket.connect_to_main_net()
```
For more information, you can click [here](https://dev-docs.ont.io/#/docs-cn/) to visit our document center.
