### ISSUE TITLE
[WIP] Simplify package namespaces

### ISSUE THREAD

**Issue by binaryflesh** [ontio/ontology-python-sdk#242]
ontology would have a more organized and cleaner package structure if the following is preferred over the current package tree. This would make the codebase more useful to future ont.io development efforts.

# ontology
> proposed package structure

## Structure
```
├───ontology/
 |    |──core/
│    |     ├───crypto/
      |      |───vm/
│    |             └───neo/
│    |                      └───abi/
│    |───contract/
│    |───wallet/
│    |       ├───account/
│    |       └───tx/
└───test/
```

examples:
```python
import ontology # imports SDKException, SDKError
from ontology.wallet import Account
from .crypto import Signature
 ...
```

This will maximize code reuse and package definitions. This will allow integration with WIP development tools to be built around use cases for ontology protocol at a high level.

# contract
>claim, native, neo, data, event

# core - non-mutable ontology components
>api, exception, error, rpc, sdk, service, client(sig), server(sigsrv), wsock

# crypto
>curve, digest, kdf, scrypt, signature

# vm
>neo, native, data, event

# wallet
>account, tx

**Comment by NashMiao** [comment]
Thanks for your contribution. let's continue to moving up.

1. In fact, `claim` is a kind of service which based on blockchain. The `ClaimRecord` has relationship with smart contract which based on NeoVm, We use this smart contract to manage claim states. The most important part in `claim` is ONT ID, a decentralized identity in blockchain based on Native VM. A claim issuer add his signature in claim, others can verify this claim by query issuer‘s public key.

2. In most condition, wallet will not be exposed to user. We recommend using `WalletManger` to handle keystore. 

```python
from ontology.ont_sdk import OntologySdk

sdk = OntologySdk()
sdk.wallet_manager.open_wallet(wallet_path)
sdk.wallet_manager.create_account(password)
acct = wallet_manager.get_account_by_b58_address('ANDfjwrUroaVtvBguDtrWKRMyxFwvVwnZD', password)
```

3. What's the most important part of `ontology-python-sdk`? Currently, it's transaction and contract invoke byte code. So, we put these part in `core` folder.

```
core
│  deploy_transaction.py
│  invoke_transaction.py
│  program.py
│  program_info.py
│  sig.py
│  transaction.py
│  __init__.py
```

4. To be honest, `abi` is difficult to use in ontology network. So, as an SDK’s maintainer, I strongly recommend all the users to use `InvokeFunction` class to create their invoke code.

```python
from ontology.smart_contract.neo_contract.invoke_function import InvokeFunction

hex_contract_address = '1ddbb682743e9d9e2b71ff419e97a9358c5c4ee9'
func = InvokeFunction('name')
result = sdk.rpc.send_neo_vm_transaction_pre_exec(hex_contract_address, None, func)
```
