### ISSUE TITLE
websocket 没反应，并且导致同步节点hang

### ISSUE THREAD

**Issue by foonsun** [ontio/ontology-python-sdk#243]
搭建的同步节点：version:'v1.6.0-beta-12-gc8504b7'
使用rpc方式获取版本等没有问题；
通过websocket获取，获取到的结果：
```
sdk.websocket.get_block_height()
Out[13]: <coroutine object WebsocketClient.get_block_height at 0x10e0ad6d0>
```
而且此时查看服务器，服务器巨卡，强制关闭ont,服务器恢复正常；

websocket的使用方式是什么呢？

**Comment by foonsun** [comment]
没问题。

**Comment by NashMiao** [comment]
Hi, can you share some experience with us?
