### ISSUE TITLE
Unable to deploy contract

### ISSUE THREAD

**Issue by WyattMufson** [ontio/ontology-python-sdk#343]
**Describe the bug**

I am unable to deploy a contract with the Python SDK following the test here: https://github.com/ontio/ontology-python-sdk/blob/cffab6fa5c23174f64d63ded44d3974e76f5d66f/tests/test_neo_vm.py#L50

**Expected Result**

I am expecting the contract to deploy correctly.

**Actual Result**

I see the following in my node:

```
2019/06/01 16:00:57.746891 [WARN ] GID 1763, TxnPool verify error: transaction verify signature fail
2019/06/01 16:00:57.746927 [WARN ] GID 1763, SendRawTransaction verified 2e63b9b6751b777ec0c681c9ee8fe8d8ececc4d00696accdf5aea7882f155059 error: transaction verify signature fail
```

**Reproduction Steps**

```python
    sdk.rpc.connect_to_localhost()
    tx = sdk.neo_vm.make_deploy_transaction(code,
                                            True,
                                            'NAME',
                                            '0.0.1',
                                            'AUTHOR',
                                            'EMAIL',
                                            'DESCRIPTION',
                                            0,
                                            22400000,
                                            acct.get_address_base58())
    tx.sign_transaction(acct)
    tx_hash = sdk.rpc.send_raw_transaction(tx)
```

**Version Information (please complete the following information):**

 - python version: Python 3.7.0
 - ontology-python-sdk version: Latest

**Additional context**

Deploying a contract from SmartX to the Private Net works as expected, pointing to an issue in the Python SDK.

**Comment by NashMiao** [comment]
@WyattMufson sorry, I will check it.

**Comment by WyattMufson** [comment]
@NashMiao thanks!

**Comment by NashMiao** [comment]
> @NashMiao thanks!

Hi, this bug has been fixed. You can update your PyPi package to `2.0.3` to fix this issue.

**Comment by WyattMufson** [comment]
That did it!
