### ISSUE TITLE
Set label for account in wallet

### ISSUE THREAD

**Issue by richiedunk** [ontio/ontology-python-sdk#396]
I'm trying to produce a wallet with multiple account, each labelled appropriately. I tried...

```
wallet = sdk.wallet_manager.open_wallet(wallet_path)
acct = sdk.wallet_manager.create_account("password")
acct.label = "Nice readable label"
```

But acct is an instance of Account not AccountData, so has no label attribute.

I tried to get the AccountData with this...

```
total_accounts = len(wallet.acounts)
wallet = sdk.wallet_manager.open_wallet(wallet_path)
acct = sdk.wallet_manager.create_account("password")
wallet.add_account(acct)
wallet.accounts[total_accounts ].label = "Nice readable label"
sdk.wallet_manager.save()
``` 

...but the label isn't saving.

Anybody have any ideas?

Thanks.

**Comment by NashMiao** [comment]
Hi, @richiedunk I think you should set label in `create_account` method.

```
def create_account(self, pwd: str, label: str = '') -> Account:
"""
This interface is used to create account based on given password and label.
"""
```

After you create account successfully, you can get `AccountData` by this interface:

```
sdk.wallet_manager.get_account_data_by_b58_address()
```

**Comment by richiedunk** [comment]
Perfect - thank you!
