### ISSUE TITLE
共识节点的govenance合约怎么调用

### ISSUE THREAD

**Issue by woshifyz** [ontio/ontology-python-sdk#58]
这里搭车问一下，我看文档申请共识节点需要stake ont，这个应该是调用govenance合约做的，这个有没有例子呀，我这边打算申请第二期的共识节点

**Comment by lucas7788** [comment]
@woshifyz 治理合约调用 pythonsdk 暂时不支持， JavaSDK和tssdk 和owallet已经支持，你可以参考那些代码中的govenance调用方法

**Comment by woshifyz** [comment]
@lucas7788  好的，多谢了
