### ISSUE TITLE
共识节点创建的流程是怎样的

### ISSUE THREAD

**Issue by woshifyz** [ontio/ontology-python-sdk#63]
我这边打算申请第二期共识节点，看代码里面的流程，需要先创建ontid，然后通过governance contract创建合约，这一块有没有文档呀。
假如我现在有一个私钥，我以什么样的流程来申请共识节点，然后抵押Ont呢？前提是我不打算用OWallet，只希望通过命令行或者代码来实现

**Comment by lucas7788** [comment]
@woshifyz  python sdk 已经支持governance合约调用，  你如果想申请共识节点，  需要通过我们的kyc，第一期的已经截止了， 我们保持联系，谢谢您对我们的关注哦

**Comment by woshifyz** [comment]
好的，你们第二期什么时候开始呢，我这边好准备下ONT，我看文档至少要10w个

**Comment by lucas7788** [comment]
@woshifyz  你可以去discord上提问
https://discordapp.com/channels/400884201773334540/400885569388937218
