### ISSUE TITLE
调用withdraw ong合约失败概率很高，为什么？

### ISSUE THREAD

**Issue by woshifyz** [ontio/ontology-python-sdk#83]
我这边调用ont合约，transfer的合约都成功了，但是withdraw ong合约有不少都失败了，例如：712b8ffecf9cc882fc81f144e9f65c5eb2d3a5030a354a19da9680a348f7a1da
为什么呢

**Comment by lucas7788** [comment]
@woshifyz  你的Python版本是3.7的吗？如果不是请用Python3.7的试试

**Comment by lucas7788** [comment]
@woshifyz  我运行了很多次withdrawong 没问题，你是怎么操作遇到的？？

**Comment by woshifyz** [comment]
> @woshifyz 你的Python版本是3.7的吗？如果不是请用Python3.7的试试

我用的是3.6， ~_~

**Comment by lucas7788** [comment]
@woshifyz  你用Python3.7的还有问题吗？？

**Comment by woshifyz** [comment]
> @woshifyz 我运行了很多次withdrawong 没问题，你是怎么操作遇到的？？

我就是调用 asset().new_withdraw_ong_transaction(...), 里面withdraw的amount我是传的 rpc get_allowance 返回的数字，我怀疑会不会是我get_allowance返回的数值比可以withdraw的数值大的缘故，但是我都是从链上读的

**Comment by woshifyz** [comment]
> @woshifyz 你用Python3.7的还有问题吗？？

我们online跑的程序都是3.6，不是很好切换

**Comment by lucas7788** [comment]
> > @woshifyz 我运行了很多次withdrawong 没问题，你是怎么操作遇到的？？
> 
> 我就是调用 asset().new_withdraw_ong_transaction(...), 里面withdraw的amount我是传的 rpc get_allowance 返回的数字，我怀疑会不会是我get_allowance返回的数值比可以withdraw的数值大的缘故，但是我都是从链上读的

@woshifyz   你检查一下是这个原因吗？

**Comment by woshifyz** [comment]
> > > @woshifyz 我运行了很多次withdrawong 没问题，你是怎么操作遇到的？？
> > 
> > 
> > 我就是调用 asset().new_withdraw_ong_transaction(...), 里面withdraw的amount我是传的 rpc get_allowance 返回的数字，我怀疑会不会是我get_allowance返回的数值比可以withdraw的数值大的缘故，但是我都是从链上读的
> 
> @woshifyz 你检查一下是这个原因吗？

我可能得试下，后面withdraw的时候amount设置的小一些，看看会不会失败
