### ISSUE TITLE
请问下怎么确认交易

### ISSUE THREAD

**Issue by senhanxiao** [ontio/ontology-python-sdk#90]
请问下怎么确认交易

**Comment by lucas7788** [comment]
@senhanxiao 
交易发出去之后，等待3秒后，根据交易hash查询事件  state是1表示成功

**Comment by senhanxiao** [comment]
@lucas7788  等待3秒 应该只是等待打包 ，我的意思的确认交易成功  区块不可逆

**Comment by xizho10** [comment]
如果有Notify就通过Notify。没有的话通过查询交易是否落账，看状态是否执行成功。
